name: build-docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: yarn

      - name: Install dependecies
        run: yarn install --frozen-lockfile

      - name: Build docs
        run: yarn typedoc

      - name: Push docs
        run: git config user.email "1008124+SeriousBug@users.noreply.github.com" && git config user.name "Actions Bot" && git add docs/ && git commit -m "Rebuild docs" && git push --force origin main:docs
