name: build-docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          registry-url: 'https://registry.npmjs.org'
          scope: '@codexteam'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependecies
        run: yarn install

      - name: Build docs
        run: yarn typedoc

      - name: Push docs
        run: git config user.email "1008124+SeriousBug@users.noreply.github.com" && git config user.name "Actions Bot" && git add docs/ && git commit -m "Rebuild docs" && git push --force origin main:docs
