name: release

on: workflow_dispatch

jobs:
  lint-test-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: yarn

      - name: Install dependecies
        run: yarn install

      - name: Test Eslint
        run: yarn lint:test

      - name: Run unit tests
        run: yarn test

      - name: Build library
        run: yarn build

      - name: Publish library
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
