name: test

on:
  push:
    branches-ignore:
      # Docs only contains the docs that have been built by the bot
      - docs

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: yarn

      - name: Install dependecies
        run: yarn install

      - name: Test Eslint
        run: yarn lint:test

      - name: Run unit tests
        run: yarn test --coverage && yarn codecov

      - name: Build library
        run: yarn build
